[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
gio = "0.21.4"
glib = "0.21.4"
image = "0.25.8"
serde = {version = "1.0.228", features = ["derive"]}
toml = "0.9.8"
